# Will not use ROI, but instead a 3D compact downsampled representation of the whole brain

In [8]:
from pathlib import Path
import nibabel as nib
import numpy as np
import h5py


In [13]:
downsample_size = 10#50
all_sessions = []
#for sess in range(1, 40+1):
for sess in range(1, 37+1): # in the shared folder, only 37 sessions
#for sess in range(1, 4+1):
    file_path = Path(f"/home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session{int(sess):02d}.hdf5")
    if file_path.is_file():
        print(f"FOUND {file_path}")
        curr_session = []
        with h5py.File(file_path, "r") as f:
            #print(f["betas"][0, :].shape) 
            #print(f["betas"].shape)# 750 trials
            #print(f["betas"][:, ::10, ::10, ::10].shape)
            #zoomed_session = zoom(f["betas"], zoom_extent) # did not work: interpolation made averything crash !
            #print(zoom_session.shape)
            curr_session += [f["betas"][:, ::downsample_size, ::downsample_size, ::downsample_size]] # BASIC DOWNSAMPLING: NO INTERPOLATION, NOTHING !
            #curr_session += [f["betas"][:, lh_idx[2][i], lh_idx[1][i], lh_idx[0][i]] for i in range(len(lh_idx[0]))]
            #curr_session += [f["betas"][:, rh_idx[2][i], rh_idx[1][i], rh_idx[0][i]] for i in range(len(rh_idx[0]))]
            curr_session = np.array(curr_session)
            print(curr_session.shape)
        all_sessions.append(curr_session)

all_sessions = np.concatenate(all_sessions, axis=1) # voxels, 750*sessions
np.save(f"nsd-data/MTL_downsampled_"+str(downsample_size)+"_full.npy", all_sessions.T)

FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session01.hdf5
(1, 750, 9, 11, 9)
FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session02.hdf5
(1, 750, 9, 11, 9)
FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session03.hdf5
(1, 750, 9, 11, 9)
FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session04.hdf5
(1, 750, 9, 11, 9)
FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session05.hdf5
(1, 750, 9, 11, 9)
FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session06.hdf5
(1, 750, 9, 11, 9)
FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj01/func1pt8mm/beta_fithrf_GLMdenoise_RR/betas_session07.hdf5
(1, 750, 9, 11, 9)
FOUND /home/jovyan/shared/NSD/nsddata_betas/ppdata/subj

In [ ]:
from scipy.ndimage import zoom #did not work on the whole dataset: interpolations on 3D snapshots made the jupyternotebook crash
array = np.array([[10,10,12,12],[5,5,6,6], [15,15,16,16], [10,10,120,12], [5,5,6,60], [10,100,12,12]] ).reshape((1,4,6))
#new_array = zoom(array, (1.0, 0.5, 1.0))
new_array = zoom(array, (1.0, 1.0, 0.5))
print(array)
print("===")
print(new_array)

#Zoom an array.
#The array is zoomed using spline interpolation of the requested order.Could be used for the entire brain maps

[[[ 10  10  12  12   5   5]
  [  6   6  15  15  16  16]
  [ 10  10 120  12   5   5]
  [  6  60  10 100  12  12]]]
===
[[[10 13  5]
  [ 6 16 16]
  [10 78  5]
  [ 6 57 12]]]
